name: GoTest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2 
        with:
          go-version: 1.19

      - name: npm
        run: sudo apt -y install nodejs

      - name: solc
        run: sudo npm install solc@0.8.3 -g

      - name: git
        run: sudo apt install git

      - name: abigen
        run: git clone https://github.com/Qitmeer/go-ethereum.git && cd go-ethereum && git checkout v1.10.21-q.1 && cd cmd/abigen && go build && sudo cp abigen /usr/local/bin/ && cd ../../..


      - name: compileSolidity
        run: solcjs --version && ls && cd testutils/cmds/ && sudo go run compile_solidity.go && cd ../../

      - name: linter
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.46.2

      - name: Build
        run: |
          export GO111MODULE=on
          go mod tidy -compat=1.19
          make qng

      - name: BaseTest
        run: |
          PATH=$PATH:$(pwd)/build/bin
          go test basetest/base_test.go

      - name: Test
        run: |
          PATH=$PATH:$(pwd)/build/bin
          go test -v ./...
      
      - name: Run ci.sh
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: ./ci.sh
